apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: web
  labels:
    app.kubernetes.io/name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: web
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
