apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-hub
  namespace: monitoring
  labels:
    app: beszel-hub
spec:
  ingressClassName: nginx
  rules:
    - host: beszel.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beszel-hub
                port:
                  number: 8090
